spring.datasource.url=jdbc:postgresql://localhost:5432/sistema_medico_2026
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080

# --- Configuracion de JWT ---
app.jwt.secret=cambia_esto_por_una_clave_larga_y_secreta_de_al_menos_32_caracteres_1234567890
app.jwt.expiracion-ms=28800000

# --- Configuracion de Correo (Gmail) ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=stuarddeleon7@gmail.com
spring.mail.password=piboejjncxmikidi
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.notificaciones.remitente=stuarddeleon7@gmail.com
